### PR TITLE
Update to apache-beam 2.24.0

### LINKED ISSUE #68: Update to apache-beam 2.24.0
Need to update apache-beam from 2.16.0 to 2.24.0 so we can use pubsub as a data source.  2.16.0 breaks with `google.api_core.exceptions.DeadlineExceeded: 504 Deadline Exceeded` when trying to use `beam.io.ReadFromPubSub`

### PR DESCRIPTION
**Pull request by pwoods25443**
Closes #68 

### Description
need apache-beam 2.24.0 to use `beam.io.ReadFromPubSub` in a pipeline

### Testing
Tested with
```
docker-compose build
docker-compose run test
```

### CODE REVIEW

**Comment by pwoods25443** [comment]
@smpiano I will rebase this one to `develop` also

**Comment by pwoods25443** [comment]
@smpiano rebased to `develop` and ready to merge

**Comment by smpiano** [comment]
@pwoods25443 The PR looks good to me.
There is a little conflict to solve before merging in `README.md` file. Is it possible to solve the conflict?

**Comment by pwoods25443** [comment]
@smpiano fixed the merge conflict with the README.  Should be good to go now

**Pull request merged**
