### PR TITLE
Refactor DatePartitionSink

### LINKED ISSUE #8: Example for normalizing vessel names
Build an example pipeline that uses https://github.com/JaeyoonPark/shipdataprocess/ to normalize `shipname` and `callsign`

connects https://github.com/GlobalFishingWatch/pipe-model/issues/13

### PR DESCRIPTION
**Pull request by bitsofbits**
# Refactor DatePartitionSink 

* Refactor `DatePartitionedWrite`r so that most of the logic is in` partitionedsink.PartitionedSink`.

* Add new subclass of `PartitionedSink`, `idpartionedsink.IDPartitionedSink` that shards based
  on the ID filed of data. 

* Allow file based, rather than directory based sharding if `shard_name_template` is set to ''
   So rather than writing to `.../KEY/PREFIX-M-of-N`, files are written to `.../PREFIX+KEY`, where
   `KEY` is the data based key (date, ID) and `+` here means concatenate.

* Merged in example code for name normalize.  Closes #8

### CODE REVIEW

**Comment by pwoods25443** [comment]
@bitsofbits this looks good.  One thing to consider is making `IdPartitionedFileSink` take a field name in the constructor so that it can be used for any arbitrarily named field that can be rendered as a string.  Maybe call it `KeyPartitionedFileSink` instead

**Comment by bitsofbits** [comment]
@pwoods25443 : that's a good thought. I changed it to take an arbitrary key and renamed it to KeyPartitionedFileSink. I also did a tad more refactoring.

**Comment by pwoods25443** [comment]
@bitsofbits this looks good.  I cleaned up a few comments and replaced the remaining references to 'id' with 'key'.  Please check and see if I broke anything in your code that uses `KeyPartitionedSink`.  If not then I think we are ok to merge

**Comment by bitsofbits** [comment]
@pwoods25443 , That works here, so feel free to merge.

Fun fact: I discovered that you can put stuff like `https://api.github.com/repos/GlobalFishingWatch/pipe-tools/tarball/refactor-partition-writers` in `requirements.txt` to pull a tarball for any branch out of github, which is handy for testing.

**Pull request merged**
